export const SET_CODE_VIEW = 'SET_CODE_VIEW';
export const SET_DIRTY = 'SET_DIRTY';
export const SET_DRAWER = 'SET_DRAWER';
export const SET_DIALOG = 'SET_DIALOG';
export const SET_PROFILE_META = 'SET_PROFILE_META';
export const NEW_QUEST = 'NEW_QUEST';
export const LOAD_QUEST = 'LOAD_QUEST';
export const DELETE_QUEST = 'DELETE_QUEST';
export const SAVE_QUEST = 'SAVE_QUEST';
export const PUBLISH_QUEST = 'PUBLISH_QUEST';
export const DOWNLOAD_QUEST = 'DOWNLOAD_QUEST';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

export const DialogIDs = {
  USER: 'USER',
  ERROR: 'ERROR',
  CONFIRM_NEW_QUEST: 'CONFIRM_NEW_QUEST',
  CONFIRM_LOAD_QUEST: 'CONFIRM_LOAD_QUEST',
  PUBLISH_QUEST: 'PUBLISH_QUEST'
};

export const CodeViews = {
  XML: 'XML',
  MARKDOWN: 'MARKDOWN'
};

export const DrawerActions = {
  OPEN: 'OPEN',
  CLOSE: 'CLOSE',
  TOGGLE: 'TOGGLE'
};

export const REQUEST_QUEST_LOAD = 'REQUEST_QUEST_LOAD';
export const RECEIVE_QUEST_LOAD = 'RECEIVE_QUEST_LOAD';

export const REQUEST_QUEST_SAVE = 'REQUEST_QUEST_SAVE';
export const RECEIVE_QUEST_SAVE = 'RECEIVE_QUEST_SAVE';

export const REQUEST_QUEST_DELETE = 'REQUEST_QUEST_DELETE';
export const RECEIVE_QUEST_DELETE = 'RECEIVE_QUEST_DELETE';

export const REQUEST_QUEST_PUBLISH = 'REQUEST_QUEST_PUBLISH';
export const RECEIVE_QUEST_PUBLISH = 'RECEIVE_QUEST_PUBLISH';

export const REQUEST_QUEST_LIST = 'REQUEST_QUEST_LIST';
export const RECEIVE_QUEST_LIST = 'RECEIVE_QUEST_LIST';