language: node_js
node_js:
- '8'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- nvm install "$(jq -r '.engines.node' package.json)" && node --version
before_deploy: "pip install awscli --upgrade --user"
cache:
  directories:
  - node_modules
deploy:
  - provider: script
    script: ./beta.sh
    skip_cleanup: true
    on:
      repo: ExpeditionRPG/expedition-quest-creator
      branch: master
