//GENERATED BY ./config/build_encounters.js
export var encounters: any = {
  "thief": {
    "name": "Thief",
    "health": 8,
    "tier": 1,
    "class": "Bandit"
  },
  "brigand": {
    "name": "Brigand",
    "health": 10,
    "tier": 1,
    "class": "Bandit"
  },
  "footpad": {
    "name": "Footpad",
    "health": 10,
    "tier": 1,
    "class": "Bandit"
  },
  "archer": {
    "name": "Archer",
    "health": 8,
    "tier": 1,
    "class": "Bandit"
  },
  "rogue": {
    "name": "Rogue",
    "health": 14,
    "tier": 2,
    "class": "Bandit"
  },
  "veteran": {
    "name": "Veteran",
    "health": 15,
    "tier": 2,
    "class": "Bandit"
  },
  "highwayman": {
    "name": "Highwayman",
    "health": 16,
    "tier": 2,
    "class": "Bandit"
  },
  "quartermaster": {
    "name": "Quartermaster",
    "health": 18,
    "tier": 2,
    "class": "Bandit"
  },
  "nightblade": {
    "name": "Nightblade",
    "health": 20,
    "tier": 3,
    "class": "Bandit"
  },
  "captain": {
    "name": "Captain",
    "health": 22,
    "tier": 4,
    "class": "Bandit"
  },
  "aspic viper": {
    "name": "Aspic Viper",
    "health": 6,
    "tier": 1,
    "class": "Beast"
  },
  "wild wolf": {
    "name": "Wild Wolf",
    "health": 8,
    "tier": 1,
    "class": "Beast"
  },
  "wild bear": {
    "name": "Wild Bear",
    "health": 10,
    "tier": 1,
    "class": "Beast"
  },
  "spider": {
    "name": "Spider",
    "health": 9,
    "tier": 1,
    "class": "Beast"
  },
  "wolfman": {
    "name": "Wolfman",
    "health": 16,
    "tier": 2,
    "class": "Beast"
  },
  "giant spider": {
    "name": "Giant Spider",
    "health": 14,
    "tier": 2,
    "class": "Beast"
  },
  "dire wolf": {
    "name": "Dire Wolf",
    "health": 17,
    "tier": 2,
    "class": "Beast"
  },
  "giant rat": {
    "name": "Giant Rat",
    "health": 15,
    "tier": 3,
    "class": "Beast"
  },
  "bear matriarch": {
    "name": "Bear Matriarch",
    "health": 20,
    "tier": 3,
    "class": "Beast"
  },
  "troll": {
    "name": "Troll",
    "health": 26,
    "tier": 4,
    "class": "Beast"
  },
  "imp": {
    "name": "Imp",
    "health": 7,
    "tier": 1,
    "class": "Fae"
  },
  "korrigan elf": {
    "name": "Korrigan Elf",
    "health": 7,
    "tier": 1,
    "class": "Fae"
  },
  "bluecap faery": {
    "name": "Bluecap Faery",
    "health": 6,
    "tier": 1,
    "class": "Fae"
  },
  "magic mushroom": {
    "name": "Magic Mushroom",
    "health": 6,
    "tier": 1,
    "class": "Fae"
  },
  "will o' the wisp": {
    "name": "Will o' the Wisp",
    "health": 6,
    "tier": 1,
    "class": "Fae"
  },
  "void imp": {
    "name": "Void Imp",
    "health": 13,
    "tier": 2,
    "class": "Fae"
  },
  "duergar": {
    "name": "Duergar",
    "health": 14,
    "tier": 2,
    "class": "Fae"
  },
  "satyr": {
    "name": "Satyr",
    "health": 20,
    "tier": 3,
    "class": "Fae"
  },
  "shapeshifter": {
    "name": "Shapeshifter",
    "health": 10,
    "tier": 3,
    "class": "Fae"
  },
  "rift walker": {
    "name": "Rift Walker",
    "health": 20,
    "tier": 4,
    "class": "Fae"
  },
  "zombie hand": {
    "name": "Zombie Hand",
    "health": 6,
    "tier": 1,
    "class": "Undead"
  },
  "skeletal rat": {
    "name": "Skeletal Rat",
    "health": 6,
    "tier": 1,
    "class": "Undead"
  },
  "floating skull": {
    "name": "Floating Skull",
    "health": 8,
    "tier": 1,
    "class": "Undead"
  },
  "zombie": {
    "name": "Zombie",
    "health": 8,
    "tier": 1,
    "class": "Undead"
  },
  "undead viking": {
    "name": "Undead Viking",
    "health": 12,
    "tier": 2,
    "class": "Undead"
  },
  "skeleton swordsman": {
    "name": "Skeleton Swordsman",
    "health": 15,
    "tier": 2,
    "class": "Undead"
  },
  "wight": {
    "name": "Wight",
    "health": 6,
    "tier": 2,
    "class": "Undead"
  },
  "vampire": {
    "name": "Vampire",
    "health": 22,
    "tier": 3,
    "class": "Undead"
  },
  "skeleton mage": {
    "name": "Skeleton Mage",
    "health": 18,
    "tier": 3,
    "class": "Undead"
  },
  "lich": {
    "name": "Lich",
    "health": 20,
    "tier": 4,
    "class": "Undead"
  }
};