//GENERATED BY ./config/build_encounters.js
export var encounters: any = {
  "Thief": {
    "name": "Thief",
    "health": 8,
    "tier": 1,
    "class": "Bandit"
  },
  "Brigand": {
    "name": "Brigand",
    "health": 10,
    "tier": 1,
    "class": "Bandit"
  },
  "Footpad": {
    "name": "Footpad",
    "health": 10,
    "tier": 1,
    "class": "Bandit"
  },
  "Archer": {
    "name": "Archer",
    "health": 8,
    "tier": 1,
    "class": "Bandit"
  },
  "Rogue": {
    "name": "Rogue",
    "health": 14,
    "tier": 2,
    "class": "Bandit"
  },
  "Veteran": {
    "name": "Veteran",
    "health": 15,
    "tier": 2,
    "class": "Bandit"
  },
  "Highwayman": {
    "name": "Highwayman",
    "health": 16,
    "tier": 2,
    "class": "Bandit"
  },
  "Quartermaster": {
    "name": "Quartermaster",
    "health": 18,
    "tier": 2,
    "class": "Bandit"
  },
  "Nightblade": {
    "name": "Nightblade",
    "health": 20,
    "tier": 3,
    "class": "Bandit"
  },
  "Captain": {
    "name": "Captain",
    "health": 22,
    "tier": 4,
    "class": "Bandit"
  },
  "Aspic Viper": {
    "name": "Aspic Viper",
    "health": 6,
    "tier": 1,
    "class": "Beast"
  },
  "Wild Wolf": {
    "name": "Wild Wolf",
    "health": 8,
    "tier": 1,
    "class": "Beast"
  },
  "Wild Bear": {
    "name": "Wild Bear",
    "health": 10,
    "tier": 1,
    "class": "Beast"
  },
  "Spider": {
    "name": "Spider",
    "health": 9,
    "tier": 1,
    "class": "Beast"
  },
  "Wolfman": {
    "name": "Wolfman",
    "health": 16,
    "tier": 2,
    "class": "Beast"
  },
  "Giant Spider": {
    "name": "Giant Spider",
    "health": 14,
    "tier": 2,
    "class": "Beast"
  },
  "Dire Wolf": {
    "name": "Dire Wolf",
    "health": 17,
    "tier": 2,
    "class": "Beast"
  },
  "Giant Rat": {
    "name": "Giant Rat",
    "health": 15,
    "tier": 3,
    "class": "Beast"
  },
  "Bear Matriarch": {
    "name": "Bear Matriarch",
    "health": 20,
    "tier": 3,
    "class": "Beast"
  },
  "Troll": {
    "name": "Troll",
    "health": 26,
    "tier": 4,
    "class": "Beast"
  },
  "Imp": {
    "name": "Imp",
    "health": 7,
    "tier": 1,
    "class": "Fae"
  },
  "Korrigan Elf": {
    "name": "Korrigan Elf",
    "health": 7,
    "tier": 1,
    "class": "Fae"
  },
  "Bluecap Faery": {
    "name": "Bluecap Faery",
    "health": 6,
    "tier": 1,
    "class": "Fae"
  },
  "Magic Mushroom": {
    "name": "Magic Mushroom",
    "health": 6,
    "tier": 1,
    "class": "Fae"
  },
  "Will o' the Wisp": {
    "name": "Will o' the Wisp",
    "health": 6,
    "tier": 1,
    "class": "Fae"
  },
  "Void Imp": {
    "name": "Void Imp",
    "health": 13,
    "tier": 2,
    "class": "Fae"
  },
  "Duergar": {
    "name": "Duergar",
    "health": 14,
    "tier": 2,
    "class": "Fae"
  },
  "Satyr": {
    "name": "Satyr",
    "health": 20,
    "tier": 3,
    "class": "Fae"
  },
  "Shapeshifter": {
    "name": "Shapeshifter",
    "health": 10,
    "tier": 3,
    "class": "Fae"
  },
  "Rift Walker": {
    "name": "Rift Walker",
    "health": 20,
    "tier": 4,
    "class": "Fae"
  },
  "Zombie Hand": {
    "name": "Zombie Hand",
    "health": 6,
    "tier": 1,
    "class": "Undead"
  },
  "Skeletal Rat": {
    "name": "Skeletal Rat",
    "health": 6,
    "tier": 1,
    "class": "Undead"
  },
  "Floating Skull": {
    "name": "Floating Skull",
    "health": 8,
    "tier": 1,
    "class": "Undead"
  },
  "Zombie": {
    "name": "Zombie",
    "health": 8,
    "tier": 1,
    "class": "Undead"
  },
  "Undead Viking": {
    "name": "Undead Viking",
    "health": 12,
    "tier": 2,
    "class": "Undead"
  },
  "Skeleton Swordsman": {
    "name": "Skeleton Swordsman",
    "health": 15,
    "tier": 2,
    "class": "Undead"
  },
  "Wight": {
    "name": "Wight",
    "health": 6,
    "tier": 2,
    "class": "Undead"
  },
  "Vampire": {
    "name": "Vampire",
    "health": 22,
    "tier": 3,
    "class": "Undead"
  },
  "Skeleton Mage": {
    "name": "Skeleton Mage",
    "health": 18,
    "tier": 3,
    "class": "Undead"
  },
  "Lich": {
    "name": "Lich",
    "health": 20,
    "tier": 4,
    "class": "Undead"
  }
};