var fs = require('fs');
var Tabletop = require('./tabletop.js');

// Result directory to store the generated files.
var dest = "./app/Encounters.tsx";

// ID of the spreadsheet to load
var docID = "1WvRrQUBRSZS6teOcbnCjAqDr-ubUNIxgiVwWGDcsZYM";


function parseEncounters(rows) {
  var result = {};
  console.log("Parsing encounters...");
  rows.forEach(function(row) {
    if (row.Comment) {
      return;
    }
    console.log(row.name);
    result[row.name] = {name: row.name, health: parseInt(row.health), tier: parseInt(row.tier), class: row.class};
  });
  return result;
}

function main(rows) {
  var encounters = parseEncounters(rows);
  fs.writeFile(dest, "//GENERATED BY ./config/build_encounters.js\nexport var encounters: any = " + JSON.stringify(encounters, null, 2) + ";", function(err) {
    if (err) {
      console.log(err);
    } else {
      console.log("Saved to " + dest);
    }
  });
}

Tabletop.init({ // jshint ignore:line
    key: docID,
    wanted: ["Encounter"],
    simpleSheet: true,
    callback: main
});
