CREATE TABLE quests (
  partition VARCHAR(32),
  id VARCHAR(255) NOT NULL,
  PRIMARY KEY(partition, id),
  questversion INT DEFAULT 1,
  questversionlastmajor INT DEFAULT 1,
  engineversion VARCHAR(128),
  publishedurl VARCHAR(2048),
  userid VARCHAR(255),
  author VARCHAR(255),
  email VARCHAR(255),
  maxplayers INT,
  maxtimeminutes INT,
  minplayers INT,
  mintimeminutes INT,
  summary VARCHAR(1024),
  title VARCHAR(255),
  url VARCHAR(2048),
  familyfriendly BOOL,
  ratingavg NUMERIC(4,2),
  ratingcount INT,
  genre VARCHAR(128),
  contentrating VARCHAR(128),
  created TIMESTAMP NULL DEFAULT NOW(),
  published TIMESTAMP NULL DEFAULT NOW(),
  tombstone TIMESTAMP NULL DEFAULT NULL,
);
