CREATE TABLE users (
  id VARCHAR(255) NOT NULL,
  PRIMARY KEY(id),
  email VARCHAR(255),
  name VARCHAR(255),
  created TIMESTAMP NULL DEFAULT NOW(),
  last_login TIMESTAMP NULL DEFAULT NOW(),
  tombstone TIMESTAMP NULL DEFAULT NULL
);
